name: Codecov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    - name: Install dependencies
      run: julia --project -e 'using Pkg; Pkg.instantiate()'
    - name: Run tests
      run: julia --project -e 'using Pkg; Pkg.test(coverage=true)'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true