name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
    test:
        name:  Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            julia_version: 
              - "1.10.3"
            os:
              - ubuntu-latest
              - macOS-latest
              - windows-latest
            arch:
              - x64
        
        steps:
            - uses: actions/checkout@v4

            - uses: julia-actions/setup-julia@v1
              with:
                version: ${{ matrix.julia_version }}
                arch: ${{ matrix.arch }}
            - uses: julia-actions/cache@v1
              with:
                cache-compiled: "true"
                cache-registries: "true"
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
              with:
                coverage: true
            - uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                